#!/usr/bin/env python3
"""
Sanity NDJSON Exporter & TypeScript Schema Generator
====================================================
Part of the WordPress-to-Sanity Vault Migration Engine.
Developed & Maintained by CultureOS Labs (https://cultureos.dev).

Features:
---------
- 100% Zero External Dependencies: Pure Python standard library (json, os, sys, argparse).
- Generates standards-compliant NDJSON bundle for `npx sanity dataset import`.
- Automatically emits production-ready TypeScript schemas for Sanity Studio v3 (`post.ts`).
- Generates Substack-standard `/archive/[ID]-[Semantic-Slug]` field structures.

Contact: hello@cultureos.dev
License: MIT
"""

import os
import sys
import json
import argparse

def export_ndjson(data_file, output_dir="exports"):
    if not os.path.exists(data_file):
        print(f"❌ Error: Data file not found: {data_file}")
        sys.exit(1)

    os.makedirs(output_dir, exist_ok=True)
    with open(data_file, "r", encoding="utf-8") as f:
        posts = json.load(f)

    ndjson_path = os.path.join(output_dir, "sanity_export.ndjson")
    print("=" * 65)
    print("📦 CultureOS Labs — Sanity NDJSON & Schema Generator")
    print(f"   Input Dataset : {data_file} ({len(posts):,} records)")
    print(f"   Output Folder : {output_dir}")
    print("=" * 65)

    with open(ndjson_path, "w", encoding="utf-8") as out:
        for p in posts:
            post_id = p.get("ID") or p.get("legacyId")
            title = p.get("Clean Title") or p.get("Title") or "Untitled Post"
            slug = p.get("CanonicalSlug") or p.get("Slug") or str(post_id)
            date = p.get("Date") or "2026-01-01"
            if len(date) == 10:
                date = f"{date}T12:00:00Z"
            elif not date.endswith("Z"):
                date = f"{date}Z"

            doc = {
                "_id": f"post-{post_id}",
                "_type": "post",
                "title": title,
                "slug": {"_type": "slug", "current": slug},
                "publishedAt": date,
                "category": p.get("Category") or "General",
                "tags": p.get("Tags") or [],
                "excerpt": p.get("Excerpt") or "",
                "legacyId": post_id,
            }

            img = p.get("First High-Res Image") or p.get("FullImg") or p.get("Thumb")
            if img:
                doc["legacyHeroImageUrl"] = img

            out.write(json.dumps(doc, ensure_ascii=False) + "\n")

    # Generate TypeScript Schema for Sanity Studio v3
    schema_path = os.path.join(output_dir, "post.ts")
    schema_code = """// Sanity Studio v3 Document Schema
// Generated by CultureOS Labs WordPress-to-Sanity Vault (https://cultureos.dev)
import { defineField, defineType } from 'sanity';

export default defineType({
  name: 'post',
  title: 'Archival Post',
  type: 'document',
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: { source: 'title', maxLength: 96 },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'publishedAt',
      title: 'Published at',
      type: 'datetime',
    }),
    defineField({
      name: 'category',
      title: 'Category',
      type: 'string',
    }),
    defineField({
      name: 'tags',
      title: 'Tags',
      type: 'array',
      of: [{ type: 'string' }],
      options: { layout: 'tags' },
    }),
    defineField({
      name: 'excerpt',
      title: 'Excerpt',
      type: 'text',
      rows: 3,
    }),
    defineField({
      name: 'legacyHeroImageUrl',
      title: 'Legacy Hero Image URL',
      type: 'url',
    }),
    defineField({
      name: 'legacyId',
      title: 'Legacy WordPress ID',
      type: 'number',
      readOnly: true,
    }),
  ],
  preview: {
    select: {
      title: 'title',
      subtitle: 'category',
      date: 'publishedAt',
    },
    prepare({ title, subtitle, date }) {
      return {
        title,
        subtitle: `${subtitle || 'Uncategorized'} • ${date ? date.slice(0, 10) : ''}`,
      };
    },
  },
});
"""
    with open(schema_path, "w", encoding="utf-8") as f:
        f.write(schema_code)

    print(f"✓ Generated NDJSON dataset : {ndjson_path}")
    print(f"✓ Generated Sanity Schema  : {schema_path}")
    print("\n👉 Next steps for technical team:")
    print("   1. Copy post.ts into your Sanity Studio schema directory.")
    print("   2. Run dataset import:")
    print(f"      npx sanity dataset import {ndjson_path} production\n")
    print("🏛️  Powered by CultureOS Labs (https://cultureos.dev)\n")

def main():
    parser = argparse.ArgumentParser(
        description="Export sanitized JSON archive to Sanity NDJSON and TypeScript schema. Maintained by CultureOS Labs (https://cultureos.dev)."
    )
    parser.add_argument("--data", default="data/sample_posts.json", help="Path to sanitized JSON dataset")
    parser.add_argument("--output", default="exports", help="Output directory (default: exports/)")
    args = parser.parse_args()

    export_ndjson(args.data, args.output)

if __name__ == "__main__":
    main()
